language: node_js
script: true
node_js:
- lts/*
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fc4d1d3cedd0_key -iv $encrypted_fc4d1d3cedd0_iv -in deploy_key.enc -out ./deploy_key -d -verbose
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- docker build . -t "nasyalnik/cats-api:travis-$TRAVIS_BUILD_NUMBER"
deploy:
  provider: script
  script: bash travis/docker
  on:
    branch: master
